# Generated by Django 4.0.5 on 2022-07-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_book',
            name='actual_return_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
